### ISSUE TITLE
Dual boot BigSur -Win with DSDT-HUANANZHI.aml

### ISSUE THREAD

**Issue by AlexLuk64** [Cclown98/X99-OPENCORE-EFI-CATALINA-BIGSUR#4]
Привет! А Вы пробовали загрузку Windows 10 из под opencore c DSDT-HUANANZHI.aml - у меня крашется.(ошибка ACPI) Не подскажите как можно поправить?

**Comment by andrescera** [comment]
with a full patched dsdt you wont be able to start windows into opencore, so you'll have to use bios boot menu in order to boot windows

**Comment by Kovbo** [comment]
I also get ACPI_BIOS_ERROR when I try to boot into Windows from opencore EFI.
I think that is because of ACPI injection from DSDT-HUANANZHI.aml. Removing this file solves the deal boot issue.

I think the only solution is to disable Mac ACPI properties injection when booting Windows.
You can simply add a few lines of code to DSDT-HUANANZHI.aml so it can check what OS loading and based on this make decision to apply some patches or not.

Most default ssdt files have this check.

 Something like this:
```
Scope (\_SB.PCI0.SBRG.EC0)
{
Method (_STA, 0, NotSerialized) // _STA: Status
{
If (_OSI ("Darwin"))
{
Return (Zero)
}
Else
{
Return (0x0F)
}
}
}



Scope (\_SB.PCI0.SBRG)
{
Device (EC)
{
Name (_HID, "ACID0001") // _HID: Hardware ID
Method (_STA, 0, NotSerialized) // _STA: Status
{
If (_OSI ("Darwin"))
{
Return (0x0F)
}
Else
{
Return (Zero)
}
}
}
}
```

I cannot do it from my side because the file is already compiled and I not have a source. Will appreciate your help.
